apiVersion: v1
entries:
  testapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-08-25T16:13:02.2071504+01:00"
    description: A Helm chart for Kubernetes
    digest: d310c620b088b2acfacb85f2ab176ed7473aeae260a93c520ef392e93cf3a54b
    name: testapp
    type: application
    urls:
    - https://github.com/markmac99/MeteorTools/testapp-0.1.0.tgz
    version: 0.1.0
generated: "2023-08-25T16:13:02.2061176+01:00"
