---
- hosts: ukmonhelper2
  gather_facts: no
  tasks:
  - name: import variables 
    include_vars: ./vars.yml
    tags: [dev,prod]
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    delegate_to: localhost
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    delegate_to: localhost
    with_items:
    - {src: '{{srcdir}}/fbCollector/fbCollector.ps1', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/fireballCollector.py', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/download_events.sh', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/config.ini', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/noimage.jpg', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/ukmda.ico', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
