---
- hosts: ukmonhelper2
  gather_facts: no
  tasks:
  - name: import variables 
    include_vars: ./vars.yml
    tags: [dev,prod]
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    delegate_to: localhost
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    delegate_to: localhost
    with_items:
    - {src: '{{srcdir}}/analysis/analysis.ini', dest: '{{destdir}}/', mode: '644', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/getStationDets.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/syncFireballData.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/multiTrackStack.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/refreshLocalCopy.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/allCameraRadiantMap.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/refresh_local_copy.sh', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/uploadOrbit.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/uploadImprovedFTP.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/helperfunctions.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/getFireballFiles.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/manualReduction.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/fireballAnalyser.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/uploadImprovedFBFiles.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/makePPallFromPP.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/analysis/getGMNData.ps1', dest: '{{destdir}}/', mode: '755', backup: no, directory_mode: no }

    - {src: '{{srcdir}}/fbCollector/fbCollector.ps1', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/fireballCollector.py', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/download_events.sh', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/config.ini', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/noimage.jpg', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
    - {src: '{{srcdir}}/fbCollector/ukmda.ico', dest: '{{destdir}}/fbCollector/', mode: '755', backup: no, directory_mode: no }
