name: automated_testing

on:
  push:
    branches:
      - main
jobs:
  #apitests:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: actions/setup-python@v4
  #      with:
  #        python-version: '3.8'
  #    - run: pip install -e .
  #    - run: chmod +x ./meteortools/tests/*.sh
  #    - run: ./meteortools/tests/runTests.sh

  rmstests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/markmac99/ubi8:latest
      env: 
        MYENV: foo
      ports:
        - 22
        - 443
    steps:
      - name: Testing container
        run: (echo $MYENV  ; zip -v ; uname -a )

