name: automated_testing

on:
  push:
    branches:
      - dev
jobs:
  apitests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./meteortools/tests/*.sh
      - run: ./meteortools/tests/runTests.sh
      
